### ISSUE TITLE
Suporte a texturas

### ISSUE THREAD

**Issue by BaraoVermelho** [gabriel-dev/chaseconv#2]
Poderia me explicar como colocou as texturas no pet rencia?

Ótimo projeto, vai me ajudar bastante em alguns quesitos de modelagem para GC.

**Comment by gabriel-dev** [comment]
Olá,

Imagino que esteja se referindo ao modelo exibido no topo do README quando fala da Rencia. 

O programa apenas exporta os dados de malha, esqueleto, mapeamento de textura e animação contidos nos arquivos P3M e FRM para o formato GLTF. Para adicionar texturas em si aos modelos, você pode usar qualquer qualquer programa de edição 3D que carregue arquivos GLTF.

No meu caso, eu usei o Blender. Tudo que fiz foi importar o arquivo GLTF e depois adicionar a textura de cada malha através do programa. Você só vai precisar ter em mãos os arquivos de textura .DDS correspondentes a cada malha. Isso você consegue descompactando os arquivos .KOM do jogo, da mesma forma que faz para conseguir os arquivos P3M e FRM.

Espero ter ajudado :)
